const bookings = [
  {
    "bookingId": "B001",
    "userId": "U001",
    "citizenId": "C001",
    "username": "JohnDoe",
    "time": "2024-03-30T15:00:00+07:00",
    "status": "Confirmed",
    "total": 200,
    "tickets": [
      {
        "ticketId": "T001",
        "flightId": "VN001",
        "userId": "U001",
        "citizenId": "C001",
        "userName": "JohnDoe",
        "seatId": "1A",
        "seatNumber": "1A",
        "ticketType": "Business",
        "price": 100,
        "departureAirportCode": "SGN",
        "departureAirportName": "Tan Son Nhat International Airport",
        "departureAirportCity": "Ho Chi Minh City",
        "departureAirportCountry": "Vietnam",
        "arrivalAirportCode": "SYD",
        "arrivalAirportName": "Sydney Kingsford Smith Airport",
        "arrivalAirportCity": "Sydney",
        "arrivalAirportCountry": "Australia",
        "estimatedTime": 60,
        "departureTime": "2024-04-01T08:00:00+07:00",
        "departureGate": "A1",
        "airplaneNumber": "VN123"
      },
      {
        "ticketId": "T002",
        "flightId": "VN001",
        "userId": "U001",
        "citizenId": "C001",
        "userName": "JohnDoe",
        "seatId": "2A",
        "seatNumber": "2A",
        "ticketType": "Economy",
        "price": 50,
        "departureAirportCode": "SGN",
        "departureAirportName": "Tan Son Nhat International Airport",
        "departureAirportCity": "Ho Chi Minh City",
        "departureAirportCountry": "Vietnam",
        "arrivalAirportCode": "SYD",
        "arrivalAirportName": "Sydney Kingsford Smith Airport",
        "arrivalAirportCity": "Sydney",
        "arrivalAirportCountry": "Australia",
        "estimatedTime": 60,
        "departureTime": "2024-04-01T08:00:00+07:00",
        "departureGate": "A1",
        "airplaneNumber": "VN123"
      }
    ]
  },
  {
    "bookingId": "B002",
    "userId": "U002",
    "citizenId": "C002",
    "username": "JaneSmith",
    "time": "2024-03-30T15:30:00+07:00",
    "status": "Confirmed",
    "total": 200,
    "tickets": [
      {
        "ticketId": "T003",
        "flightId": "VN002",
        "userId": "U002",
        "citizenId": "C002",
        "userName": "JaneSmith",
        "seatId": "3A",
        "seatNumber": "3A",
        "ticketType": "Business",
        "price": 100,
        "departureAirportCode": "SGN",
        "departureAirportName": "Tan Son Nhat International Airport",
        "departureAirportCity": "Ho Chi Minh City",
        "departureAirportCountry": "Vietnam",
        "arrivalAirportCode": "HND",
        "arrivalAirportName": "Haneda Airport",
        "arrivalAirportCity": "Tokyo",
        "arrivalAirportCountry": "Japan",
        "estimatedTime": 60,
        "departureTime": "2024-04-01T08:00:00+07:00",
        "departureGate": "B2",
        "airplaneNumber": "VN456"
      },
      {
        "ticketId": "T004",
        "flightId": "VN002",
        "userId": "U002",
        "citizenId": "C002",
        "userName": "JaneSmith",
        "seatId": "4A",
        "seatNumber": "4A",
        "ticketType": "Economy",
        "price": 50,
        "departureAirportCode": "SGN",
        "departureAirportName": "Tan Son Nhat International Airport",
        "departureAirportCity": "Ho Chi Minh City",
        "departureAirportCountry": "Vietnam",
        "arrivalAirportCode": "HND",
        "arrivalAirportName": "Haneda Airport",
        "arrivalAirportCity": "Tokyo",
        "arrivalAirportCountry": "Japan",
        "estimatedTime": 60,
        "departureTime": "2024-04-01T08:00:00+07:00",
        "departureGate": "B2",
        "airplaneNumber": "VN456"
      }
    ]
  },
  {
    "bookingId": "B003",
    "userId": "U003",
    "citizenId": "C003",
    "username": "AliceBrown",
    "time": "2024-03-30T16:00:00+07:00",
    "status": "Confirmed",
    "total": 200,
    "tickets": [
      {
        "ticketId": "T005",
        "flightId": "VN004",
        "userId": "U003",
        "citizenId": "C003",
        "userName": "AliceBrown",
        "seatId": "7A",
        "seatNumber": "7A",
        "ticketType": "Business",
        "price": 100,
        "departureAirportCode": "HAN",
        "departureAirportName": "Noi Bai International Airport",
        "departureAirportCity": "Hanoi",
        "departureAirportCountry": "Vietnam",
        "arrivalAirportCode": "HND",
        "arrivalAirportName": "Haneda Airport",
        "arrivalAirportCity": "Tokyo",
        "arrivalAirportCountry": "Japan",
        "estimatedTime": 60,
        "departureTime": "2024-04-01T08:00:00+07:00",
        "departureGate": "D4",
        "airplaneNumber": "VN234"
      },
      {
        "ticketId": "T006",
        "flightId": "VN004",
        "userId": "U003",
        "citizenId": "C003",
        "userName": "AliceBrown",
        "seatId": "7B",
        "seatNumber": "7B",
        "ticketType": "Business",
        "price": 100,
        "departureAirportCode": "HAN",
        "departureAirportName": "Noi Bai International Airport",
        "departureAirportCity": "Hanoi",
        "departureAirportCountry": "Vietnam",
        "arrivalAirportCode": "HND",
        "arrivalAirportName": "Haneda Airport",
        "arrivalAirportCity": "Tokyo",
        "arrivalAirportCountry": "Japan",
        "estimatedTime": 60,
        "departureTime": "2024-04-01T08:00:00+07:00",
        "departureGate": "D4",
        "airplaneNumber": "VN234"
      }
    ]
  }
]

export default bookings